language: node_js
node_js:
  - "10"
git:
  depth: 5
  quiet: true
before_install:
  - rm -rf .git
  - npm set audit false
  - cd ..
  - git clone https://github.com/theme-suka/hexo-theme-unit-test.git --depth=2
  - rm -rf hexo-theme-unit-test/.git
  - cd hexo-theme-unit-test
install:
  - npm i > /dev/null
  - chmod +x ./install-theme.sh
  - ./install-theme.sh
script:
  - chmod +x ./build.sh
  - ./build.sh
  - chmod +x ./deploy.sh
  - ./deploy.sh > /dev/null
cache:
  directories:
  - themes/suka/node_modules
  - node_modules
  timeout: 60
