# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
head:
  # You should use a image/x-icon type icon and configure it here.
  favicon: favicon.ico
  high_res_favicon: favicon.ico
  # It defined meta keyword.
  keywords: 12345
  android_chrome_color: '#000000'
  site_verification:
    google:
    baidu:
  pwa_manifest:
  open_search:

footer:
  # Copyright Since
  # Specify the date when the site was setup.
  # For example, if you set it as 2015, then footer will show something like '© 2015 - 2018'
  # If you just want to show it like '© 2018' onlt, simly leave it blank as not defined.
  copyright_since:
  # Footer Text
  # You can specify the text you want to show in footer, HTML tag is supported.
  # For example, you can setup ICP license number as:
  #   custom_text: '<a href="http://www.miitbeian.gov.cn" rel="nofollow noopener noreferrer">某ICP备xxxxxxxx号-x</a>'

  custom_text:
    - '<a href="http://www.miitbeian.gov.cn" rel="nofollow noopener noreferrer">某ICP备xxxxxxxx号-x</a>'
    - 'Hosted on XXXXX Pages'
# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------


img:
  avatar:

uiux:
  slogan: 孰是孰非就让人评说 终不过 成王败寇
  link_color:
  primary_color:
  secondary_color:
  bg_color: '#fcfcfc'

post:
  entry_excerpt: 120

sns:
  twttier:

# SNS Share Switch
sns_share:
  twitter: true
  facebook: true
  googleplus: true
  weibo: true
  linkedin: false
  qq: false
  telegram: false

nav:
  archives:
    use: true
  rss:
    use: true
  search:
    use: true
    link: /search
  pages:


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------


analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

# ---------------------------------------------------------------
# Vendors Settings
# ---------------------------------------------------------------
# Set a CDN address for the vendor you want to customize.
# Be aware that you should use the same version as internal ones to avoid potential problems.
# We prefer you using the https protocol of CDN files whether you enable https on your site or not.
vendors:
  # hexo-theme-suka
  # https://github.com/SukkaW/hexo-theme-suka
  suka:
    style_css:
    local_search_js:
  # Spectre.css
  # https://picturepan2.github.io/spectre/
  # Version: 0.5.3
  spectre:
    spectre_css:
    spectre_exp_css:
    spectre_icons_css:
  # Lazyload
  # https://github.com/verlok/lazyload
  # Version: 8.9.0
  lazyload:


# ---------------------------------------------------------------
# !!ATTENTION!!
# Do Not Modify Below This Line, unless you know what you are doing!
# ---------------------------------------------------------------
verison: 0.0.1
old_verison: