# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
head:
  # You should use a image/x-icon type icon and configure it here.
  favicon: favicon.ico
  high_res_favicon: favicon.ico
  # It defined meta keyword.
  keywords: 12345
  android_chrome_color: '#000000'
  site_verification:
    google:
    baidu:
  pwa_manifest:
  open_search:

footer:
  # Copyright Since
  # Specify the date when the site was setup.
  # For example, if you set it as 2015, then footer will show something like '© 2015 - 2018'
  # If you just want to show it like '© 2018' onlt, simly leave it blank as not defined.
  copyright_since:
  # Footer Text
  # You can specify the text you want to show in footer, HTML tag is supported.
  # For example, you can setup ICP license number as:
  #   custom_text: '<a href="http://www.miitbeian.gov.cn" rel="nofollow noopener noreferrer">某ICP备xxxxxxxx号-x</a>'

  custom_text:
    - '<a href="http://www.miitbeian.gov.cn" rel="nofollow noopener noreferrer">某ICP备xxxxxxxx号-x</a>'
    - 'Hosted on XXXXX Pages'
# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------


img:
  avatar:

uiux:
  slogan: 孰是孰非就让人评说 终不过 成王败寇
  link_color:
  primary_color:
  secondary_color:
  bg_color: '#fcfcfc'

post:
  entry_excerpt: 120
  expire: true
  share: true
  # Post License
  # You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
  #   For example, you can setup a CC license as:
  #       license: 'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
  # You can also use Front-Matter `license` to override this setting
  # or use Front-Matter `hide_license: true` to hide license on spefic post
  license: 'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'

nav:
  home:
    use: true
  archives:
    use: true
  rss:
    use: true
  share:
    use: true
  search:
    use: true
    link: /search
  pages:

sns_share:
  weibo: true
  facebook: true
  twitter: true
  telegram: true
  googleplus: true
  linkedin: true
  qq: true

qrcode:
  index_share: true
  post_share: true

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------
# Comment Systems
# Available value of "use":
#     disqus | disqus_proxy | disqus_click | changyan | livere | gitment | gitalk | valine
# If you want to use gitment or gitalk,you should get the client_id and client_secret form https://github.com/settings/applications/new
# If you want to use valine,you should get the app_id and app_key form https://leancloud.cn ,more setting please see https://valine.js.org
comment:
  use:
  disqus:
    shortname: suka # disqus shortname
  disqus_proxy:
    shortname:
    apikey: E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F # The pubkey of your application
    proxy: https://cors-anywhere.herokuapp.com/disqus.com/api/3.0/ # The proxy of https://disqus.com/api/3.0/
  changyan:
    appid:
    conf:
    thread_key_type: path # id | path. Only when you generate static id for each post before you using 'id'
  livere:
    data_uid:
  gitment:
    repo:
    owner:
    client_id:
    client_secret:
  gitalk:
    repo:
    owner:
    client_id:
    client_secret:
  valine:
    leancloud_appId:  # leancloud application app id
    leancloud_appKey:  # leancloud application app key
    notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
    verify: false # valine verify code (true/false)
    pageSize: 10 # comment list page size
    avatar: identicon # gravatar style https://valine.js.org/#/avatar
    lang: zh-cn # i18n
    placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
    guest_info: nick,mail,link #valine comment header info
  wildfire:
    database_provider: firebase # firebase or wilddog
    wilddog_site_id:
    firebase_api_key:
    firebase_auth_domain:
    firebase_database_url:
    firebase_project_id:
    firebase_storage_bucket:
    firebase_messaging_sender_id:
    theme: light # light or dark
    locale: en # en or zh-CN

analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

busuanzi:
  enable: true
  site:
    enable: true
    type: pv # pv | uv
  post_pv:
    enable: true

# ---------------------------------------------------------------
# Vendors Settings
# ---------------------------------------------------------------
# Set a CDN address for the vendor you want to customize.
# Be aware that you should use the same version as internal ones to avoid potential problems.
# We prefer you using the https protocol of CDN files whether you enable https on your site or not.
vendors:
  # hexo-theme-suka
  # https://github.com/SukkaW/hexo-theme-suka
  suka:
    style_css:
    local_search_js:
  # Spectre.css
  # https://picturepan2.github.io/spectre/
  # Version: 0.5.3
  spectre:
    spectre_css:
    spectre_exp_css:
    spectre_icons_css:
  # Prism & Prism Theme
  # https://github.com/PrismJS/prism/ https://github.com/PrismJS/prism-themes
  # Prism Version: 1.15.0 | Prism Theme Version: 1.0.1
  prism:
    theme:
    line_number:
  # Lazyload
  # https://github.com/verlok/lazyload
  # Version: 8.9.0
  lazyload:
  # Busuanzi
  # https://busuanzi.ibruce.info
  busuanzi:


# ---------------------------------------------------------------
# !!ATTENTION!!
# Do Not Modify Below This Line, unless you know what you are doing!
# ---------------------------------------------------------------
verison: 0.0.1
old_verison: